# Generated by Django 5.1 on 2024-08-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_alter_productregister_bom_submission_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
