# Generated by Django 5.1 on 2024-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='allocated_mentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
