# Generated by Django 5.1 on 2024-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_productregister_allocated_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='final_review_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productregister',
            name='first_review_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productregister',
            name='member_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productregister',
            name='member_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productregister',
            name='member_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productregister',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productregister',
            name='second_review_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
