# Generated by Django 5.1 on 2024-09-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_productregister_final_review_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='Project_Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
