# Generated by Django 5.1 on 2024-09-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_productregister_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='project_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
