# Generated by Django 5.1 on 2025-01-04 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0009_alter_productregister_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='approval_form',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
